### PR TITLE
dark-theme-progress-dialog

### PR DESCRIPTION
**Pull request by danger-ahead**
Fix Issue #1 

[fix video](https://drive.google.com/file/d/18wsdJVZGuot6PWc-45713FZ2z6qrLaFx/view?usp=sharing)

### CODE REVIEW

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
Hey there @danger-ahead! Awesome work :)

Just some small things I noticed:

 - Overriding the style changed the `ProgessDialog` overall! Can you change `Theme.AppCompat.DayNight.Dialog` to `Theme.AppCompat.DayNight.Dialog.Alert`? 
 - `ProgessDialogTheme` in `styles.xml` has a typo in it!
 - Also, why was the two `ProgressDialog` variables were changed to two lines?!

Awesome work again! Please look into the above points.

Thanks! - Vishnu

**Comment by VishnuSanal** [comment]
Why did this get closed?! @danger-ahead

**Comment by danger-ahead** [comment]
@VishnuSanal I am quite new to GitHub. I reverted the commit (that contained the typo and the wrong style). And the PR closed automatically. Sorry for that. I've understood the working now. 😓

**Comment by VishnuSanal** [comment]
Test

**Comment by VishnuSanal** [comment]
@VishnuSanal Test comment

**Pull request closed without merging**
